server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: sm-service
          uri: http://192.168.100.162:8891
          predicates:
            - Path=/sm/**
        - id: dr-service
          uri: http://192.168.100.162:8889
          predicates:
            - Path=/dr/**
        - id: tm-service
          uri: http://192.168.100.162:8890
          predicates:
            - Path=/tm/**
        - id: cm-service
          uri: lb://CM-SERVICE
          predicates:
            - Path=/cm/**

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - "gateway"

#spring:
#  application:
#    name: gateway-service
#
#  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://192.168.100.162:8080"
#            allow-credentials: true
#            allowedHeaders:
#              - x-requested-with
#              - authorization
#              - content-type
#              - credential
#              - X-AUTH-TOKEN
#              - X-CSRF-TOKEN
#            allowedMethods:
#              - POST
#              - GET
#              - PUT
#              - OPTIONS
#              - DELETE
#      routes:
#        id: SM-SERVICE
#        uri: http://192.168.100.162:8888
#        filters:
#          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#        predicates: path=/hello3

